swagger: '2.0'
host: swagger.io
basePath: /
info:
  title: Swagger Sample App
  description: This is a sample server Petstore server.
  termsOfService: http://swagger.io/terms/
  contact:
    name: API Support
    url: http://www.swagger.io/support
    email: support@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.1

schemes:
 - https

consumes:
  - application/json

produces:
  - application/json

paths:
  /pets:
    get:
      summary: Get a list of pets
      description: Retrieve a list of pets
      responses:
        200:
          description: Returns a list of pets.
          schema:
            $ref: '#/definitions/Pets'
    post:
      summary: Add pet to DB
      description: Results in new pet information added to the DB
      parameters:
        - name: pet
          in: body
          description: Pet details
          schema:
            required: [name, status]
            properties:
              name:
                type: string
                description: The pet name
              status:
                type: string
                description: The pet status
      responses:
        201:
          description: Created new pet in the database
          schema:
            required: [pet-id]
            properties:
              pet-id:
                type: number
                description: Unique Id for the pet in the system
  /pets/{pet-id}:
    parameters:
      - $ref: '#/parameters/pet-id'
    get:
      summary: Retrieve pet details
      description: Get details of a pet previously registered
      responses:
        200:
          description: Returns a specific talk
          schema:
            $ref: '#/definitions/Pet'
          examples:
            application/json:
              {
                id: 12345,
                name: "pythagoras",
                status: "Adopted"
              }
    put:
      summary: Update pet details
      description: Update details for previously registered pet
      parameters:
        - name: pet
          in: body
          description: Details to update
          schema:
            $ref: '#/definitions/Pet'
      responses:
        200:
          description: Pet details updated
    delete:
      summary: Remove a pet
      description: Remove the pet details from DB
      responses:
        200:
          description: Pet removed

parameters:
  pet-id:
    name: pet-id
    in: path
    description: Pet identifier
    type: number
    required: true

definitions:
  Pet:
    type: object
    required: [name, status]
    properties:
      id:
        type: string
        description: Pet unique id
      name:
        type: string
        description: Pet name
      status:
        type: string
        description: Adoption status
  Pets:
    type: array
    items:
      $ref: "#/definitions/Pet"